### PR TITLE
Allow load terraformsh.conf from parent folders and add some debug messages

### PR DESCRIPTION
**Pull request by Th0masL**
Hi !

First, thank you for this very nice wrapper !

Your bash skills are definitely better than mine, and the script is written in a very efficient way, so I was kind of struggling to understand precisely its behavior 😄 

In order to help understanding more precisely what it is doing, I've added couple of extra lines of debug messages.

Also, I was thinking that it would be nice to be able to load a `terraformsh.conf` file from a parent folder of where the script is running.

Please find this small PR that cover all those changes.

Here is an example of a folder structure:
```
$cd /tmp/foo
$ tree
.
└── bar
    ├── terraformsh.conf
    └── foo2
        └── bar2
            ├── main.tf
            └── terraformsh.conf

3 directories, 3 files
```

As you can see in the logs below, only the first `terraformsh.conf` file will be able to be loaded.

```
$ cd /tmp/foo/bar/foo2/bar2
$ export DEBUG=1
$ terraformsh
terraformsh: Debug: Searching for terraform.sh.tfvars files in current and parent folders ...
terraformsh: Debug: Searching for terraform.sh.tfvars.json files in current and parent folders ...
terraformsh: Debug: Searching for backend.sh.tfvars files in current and parent folders ...
terraformsh: Debug: Searching for default terraformsh config file /etc/terraformsh ...
terraformsh: Debug: Searching for default terraformsh config file /Users/thomas/.terraformshrc ...
terraformsh: Debug: Searching for default terraformsh config file ./.terraformshrc ...
terraformsh: Debug: Searching for default terraformsh config file terraformsh.conf in current and parent folders ...
terraformsh: Debug: Found file /tmp/foo/bar/foo2/bar2/terraformsh.conf ...
terraformsh: Debug: Loading first/best match for terraformsh.conf bash file: /tmp/foo/bar/foo2/bar2/terraformsh.conf ...
```

If you delete the file in the current folder, the file of the parents folder will be loaded.

I hope you won't mind this change ! Let me know if there's anything that is not correct.

I might suggest some other small improvements in the future 🙂 

Thanks

Thomas

### CODE REVIEW

**Comment by Th0masL** [comment]
Hey @peterwwillis @pwillis-els !
It seems like you're not active that much nowadays on GitHub.

I'll keep this PR as draft, and wait for the previous/first one to be merged, as it's going to become harder tomake many PRs on the same file if we can't get the earlier PRs merged.

Meanwhile I'll continue working on improving the script on my side, and I'll be happy to open more PRs to merge the improvements back to your repo once you're back 🙂 

Thanks !

**Comment by pwillis-els** [comment]
Hi @Th0masL, sorry I didn't see your original PR message! I'll review these changes and get back to you. I'll also check out the other PR.

**Comment by Th0masL** [comment]
Hey! Thanks for your answer!

~This PR is a bit outdated now, as I've added couple of extra things on my side.~

~I'll open some new PRs so we can eventually get things merged.~

**Comment by Th0masL** [comment]
Actually no, I think I rebased this PR with the recent changes, we should be good to review and merge it.

Feel free to let me know if you see anything that is not correct.

**Comment by Th0masL** [comment]
And if you prefer I can split the changes in smaller PRs, with only the "Load from parents folders" functionality first, and then Debug improvement.

**Comment by Th0masL** [comment]
I'll re-base this PR after we have added some other minor improvements.

**Pull request closed without merging**
